### ISSUE TITLE
Docker build problem

### ISSUE THREAD

**Issue by billmoyers** [helq/tensorflow-haskell-deptyped#1]
706431224c85b2164fe815331046f6258b1afa3e seems to have broken the build for me when building using the docker build (https://github.com/tensorflow/haskell) with:

```
> stack --docker --docker-image=$IMAGE_NAME build
Unable to parse cabal file .../tensorflow-haskell-deptyped/tensorflow-deptyped.cabal: NoParse "license" 9
```

Just moving the comment to the next line fixes it, not sure if you're using a different build environment where that is necessary based on the commit comment?

**Comment by helq** [comment]
Sorry for the very late reply, I didn't receive any notification from github, I gotta change github's preferences.

Yeah, I noticed that too. Cabal or Stack don't parse comments in cabal files as I expected. It ignored the license completely, which meant that it never compile the code, but everything was alright.

I've already fixed the bug at in the commit d099b3ada29d5af1970315abdef01a1e5ad5ed04.

Thanks for issuing and happy new year!
