### ISSUE TITLE
Project doesn't build if TF version later than v1.3

### ISSUE THREAD

**Issue by vertexcite** [helq/tensorflow-haskell-deptyped#2]

**Comment by helq** [comment]
To make it work with more recent versions of tensorflow, you need to change the commit to the repo https://github.com/tensorflow/haskell.git inside the file "stack.yaml".
Also, the `extra-deps` from the main repo (https://github.com/tensorflow/haskell.git) should coincide.

I can't check if those changes are the mininum changes to make the project run with newer versions. I'll check it later, in a week or so.

**Comment by helq** [comment]
I've updated the repo again 618ab5d. So this issue has been solved twice XD (I don't know why I didn't close it the first time).

Anyway, if anybody notices this repo out of sync with tensorflow/haskell, you can reopen the issue.
