### ISSUE TITLE
Remove `batchMatMul` from API

### ISSUE THREAD

**Issue by helq** [helq/tensorflow-haskell-deptyped#7]
I fail to see the difference between `matMul` and `batchMatMul`. If they are the same, why should we keep the later?

According to the Python documentation there is only `matMul`

https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

In fact, it seems `batchMatMul` was deprecated and removed from the Python API long time ago:

https://stackoverflow.com/a/43819275

**Comment by vilunov** [comment]
Python API differs from low-level TensorFlow API, `batchMatMul` is a generalized version of `matMul`: `matMul` accepts only 2-d tensors (given their shapes allow them to be multiplied), `batchMatMul` accepts any-d tensors by multiplying them only in the last two dimensions, while other dimensions must be the same. I've tested this and TensorFlow throws a runtime exception with `matMul`ing tensors with shapes such as `[1, 2, 3]` and `[1, 3, 4]`, while `batchMatMul` allows this.

It's possible to remove `matMul` completely and rename `batchMatMul` to `matMul`, seeing as the behavior is the same.

**Comment by vilunov** [comment]
Here's the code of Python API, which calls TF's `batchMatMul`: https://github.com/tensorflow/tensorflow/blob/v1.14.0/tensorflow/python/ops/math_ops.py#L2597

**Comment by helq** [comment]
I see... In that case no operation should be removed.

I was assuming that the Python API agreed with the C++ API, my bad.

I've just pushed a fix (21629f0) for the type of `matMul`, which I wrongly assumed to be the same of `batchMatMul`.
